In [34]:
import pandas as pd

df = pd.read_csv('data2.csv')

print(df.head())

   userID  years_exp_total  number_of_employers  years_exp_relevant  \
0       0               10                    3                   5   
1       1                3                    4                   0   
2       2                3                    4                   0   
3       3                7                    2                   6   
4       4               12                    1                   6   

   degree_ba  degree_ms  degree_phd  internal_reference  external_web_indeed  \
0          1          0           0                   0                    1   
1          1          0           0                   0                    0   
2          1          0           0                   1                    0   
3          1          0           0                   1                    0   
4          1          0           0                   1                    0   

   external_web_glassdoor  success  
0                       0        0  
1                 

In [35]:
df = df.drop('userID', axis=1)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
y=df['success']

In [38]:
x=df.drop(['success'], axis=1)

In [39]:
x.as_matrix(columns=None)

array([[10,  3,  5, ...,  0,  1,  0],
       [ 3,  4,  0, ...,  0,  0,  1],
       [ 3,  4,  0, ...,  1,  0,  0],
       ..., 
       [ 7,  2,  6, ...,  1,  0,  0],
       [10,  3,  4, ...,  1,  0,  0],
       [12,  1, 11, ...,  1,  0,  0]], dtype=int64)

In [40]:
import numpy as np

In [41]:
X=np.asarray(x)

In [42]:
X

array([[10,  3,  5, ...,  0,  1,  0],
       [ 3,  4,  0, ...,  0,  0,  1],
       [ 3,  4,  0, ...,  1,  0,  0],
       ..., 
       [ 7,  2,  6, ...,  1,  0,  0],
       [10,  3,  4, ...,  1,  0,  0],
       [12,  1, 11, ...,  1,  0,  0]], dtype=int64)

In [43]:
X.reshape(1,-1)

array([[10,  3,  5, ...,  1,  0,  0]], dtype=int64)

In [44]:
from sklearn import svm

In [45]:
clf = svm.SVC()

In [46]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [71]:
a=clf.predict([2,1,0,1,0,0,0,0,1])

C:\Users\shorav\Anaconda2\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [72]:
a

array([1], dtype=int64)